Package id 1551 current

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,21 +1,3 @@
-sudo: required
-latex: false
-warnings_are_errors: false
-os:
-  - linux
-  - osx
-compiler:
-  - clang
-
-matrix:
- allow_failures:
-   - os: osx
-   - r: devel
-   - r: 3.7
-
-
-dist: trusty
-
 language: r
 cache: packages
 warnings_are_errors: true
@@ -26,6 +8,8 @@ dist: trusty
 addons:
   apt:
     packages:
+    - libcurl4-openssl-dev
+    - libxml2-dev
     - libfftw3-dev
     - libgsl0-dev
     - libgsl0ldbl
@@ -34,15 +18,14 @@ os:
 - osx
 osx_image: xcode9
 r:
-  - 3.2
-  - 3.3
-  - 3.4
-  - 3.5
-  - 3.6
-  - 3.7
-  - release
-  - devel
-
+- 3.3
+- 3.4
+- 3.5
+- release
+- devel
+matrix:
+  allow_failures:
+  - r: devel
 env:
   global:
   - R_BUILD_ARGS="--no-manual"
@@ -53,24 +36,70 @@ env:
   - DISPLAY=:99.0
   - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
 before_install:
-  - ulimit -n 2048
-  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
-  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
-  - wget -O antsr_travis.sh http://bit.ly/antsr_travis_sh
-  - chmod +x antsr_travis.sh
-  - . ./antsr_travis.sh
-  - rm antsr_travis.sh
-  - v8_install
-  - Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"
-  - Rscript -e "install.packages( c('magrittr','testthat','knitr','rmarkdown','covr','devtools', 'desc',  'remotes', 'colormap' ), repos=c(CRAN='https://cran.rstudio.com'))"
-  - Rscript -e 'install.packages("rsvd")'
-  - Rscript -e 'install.packages("magic")'
-  - Rscript -e 'install.packages("ggplot2")'
-  - Rscript -e 'install.packages("psych")'
-  - Rscript -e 'install.packages("randomForest")'
-  - Rscript -e "install.packages(c('lmPerm', 'multcomp', 'nparcomp', 'RcppArmadillo', 'sandwitch', 'TH.data', 'zoo'), type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"
-  - cat DESCRIPTION
-  
+- ulimit -n 2048
+- export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
+- export PROJ_DIR=`basename $PWD`
+- echo "travis_wait*\.log$" >> .Rbuildignore
+- fname=travis_helpers.sh
+- wget -O ${fname} http://bit.ly/travis_helpers
+- cat ${fname}; source ${fname}; rm ${fname}
+- cat DESCRIPTION
+- start_xvfb ;
+- v8_install ;
+- dcmtk_install ;
+- export rver=`r_version`; echo $rver ;
+- export PACKAGE_NAME=`package_name`
+- export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
+- remove_neuroc_packages
+- export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
+- x=`export_clang_cxx`; eval ${x}
+- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
+- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
+- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
+- clang_cxx
+- export cmake_version="3.11"
+- cmake --version
+- x=`cmake_setup`; echo "${x}"; eval ${x};
+- cmake --version
+- export ants_user=neuroconductor
+- echo "Installing Missing Deps ITKR"
+- install_missing_remote_deps_all ${ants_user}/ITKR
+- gh_binary_install ${ants_user}/ITKR ;
+- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}"
+  == "ANTsR" ]]; then Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type =
+  'source', repo = 'http://cran.rstudio.com')" ; fi
+- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]]; then export
+  R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ; export R_CHECK_ARGS="--no-vignettes
+  ${R_CHECK_ARGS}" ; fi
+- if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ANTsRCore"
+  ; install_missing_remote_deps_all ${ants_user}/ANTsRCore; gh_binary_install_passive
+  ${ants_user}/ANTsRCore ; fi
+- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then echo
+  "Installing Missing Deps ANTsR" ; install_missing_remote_deps_all ${ants_user}/ANTsR
+  ; gh_binary_install_passive ${ants_user}/ANTsR ; fi
+- if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=false
+  ; fi
+- cat DESCRIPTION
+- install_remotes_no_dep
+- cat DESCRIPTION
+- echo $PATH ;
+- install_deps_no_suggests
+- install_python_requirements ;
+- R CMD javareconf ;
+- travis_run_cache
+script:
+- x=`export_clang_cxx`; eval ${x}
+- travis_wait 100 R CMD build ${R_BUILD_ARGS} .
+- rm -f travis_wait*.log
+- PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
+- ls
+- travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+- rm -f travis_wait*.log
+- if [[ $CHECK_RET -ne 0 ]]; then echo "R CMD check failed"; check_fail; dump_logs;
+  travis_terminate 1; fi
+- check_warnings
+after_success:
+- dump_logs
 after_failure:
 - dump_logs
 before_deploy:
@@ -86,12 +115,16 @@ deploy:
   provider: releases
   skip_cleanup: true
   file_glob: true
+  overwrite: true
   file: "${PACKAGE_NAME}*.t*gz"
   on:
     tags: true
   api-key:
-    secure: JV/lmBxXecvsNLXMDWGutqJXN3stXLew4Jh+X20C8dzJ0WHBVrKZRJXhaDo7OGmBijQ9PJM7UkGFpNNq0eUuiMxwddwDO0Hjd19Wf5GkxwEQXmZLZ56pMaPzCIebwz5AiHzVVwRixzVGMnwB+JIPuJSYccEhg6ppRe+OO+tZheVc+HQl5+JZWkPVjVfmrvXsUbfn9qRJkd5DJWn/Ju600xvFPTEoougFU7MnfHKOUxxl4NfVaK/YuAVak/YhOJtvbMGhk/jVx22zbdgu+qbYDUBzf9aIvMSKw0uTU/H+k9LxOnIYnu3zYuzeYfAE+nSM6HtXY/LvnkdsQacLksro+zakqfSUaQrBiikx6XaFcNRJE5f08Y0V7nWvTlfDNmgV9GJUvKHjcdAgXV5ZAxhC69YnyQ/fxO59mooNiplfO4Ip8WsrHqapJp4b8EVVIkRVQrJksFnALv0iHoDhYDBNsMMAtXUNI+ZDlOlLvJlcUEHLxE6w8KQi4sojQyE6Of6PaMGyOee+Qo0QGebXTqq5U4PQu5TaKLKIi7jXmXRe8lS01L5HD16cqgrByF81KczQ3Ttui75E/PAQgN33vhfnEEfPM5gYOhk5IJxtU6rYeoPTFVGV0znistJC2th87eJIqL8lWesyVnc312vBLrcHLMx6L8XIA8o0uqkpFJURn6Q=
+    secure: 2+4Mbsl8zfVm9Yfi1krg6CO27UF9oWzElTKjL2G/MsrYxhqdkCHWQZSU5UqaurEc+U7TGl1z47oIsLXWtNOkrE956dnGxXVGP3EyK6RN+TusAkeGZKb38ErRs8FMyQtheqttiv3g6A2E32OGdJOmwcg1o0qucwdjcDhZ4D59oOACPCL1eWcUeNPwMCQbDYWiRpVMGCxExMHg1okXcBumyko5R9cPmnuc/TwKvGbIGFvbnddraaS6DSW8qgsP/grCZ7znj10aT5qO/M0P4GB8WLifoDmf1FoJc3AZpeRCMKQVtI+ZaK4FSDGE/OJx6JL228RWVSMJjM/Ir0P0JKEjs5LkD8qqtARKT2YNhXv5xcDi/jKIHjtULfWiXRtf8/FA5dSQ8/s7lx5JDk9AZlh9uUYktUqELyW1qHASmcKfgCwXtax5zWZUTec0oGK/n3XpM2FfsC8t4MWBBKcKE9T2UKdBmhlk09hh5hlmYbfBluPLNPKql0qKIBB8opqHd39bF5D/7bW5wMse+F3v9PAT0vie8pS34mqXUwc/ezS0sbzqMsxzNOVC1+GWiVDwhYTDk3aCkbuaXmUwDdkuX07FIY3cdoXzyfha7TCWKVhum6udoPEltTGFbCgTFY4BTW53VKgpM0+So/fdG1Ztux02RIGkmG+MC3D44shoZzFMnMQ=
 after_deploy:
+- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
+  else run_coverage=; fi;
 - if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}"
-  != "ANTsRCore" ]]; then if [[ "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then
-  Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)' ; fi fi
+  != "ANTsRCore" && -z "${run_coverage}" ]]; then if [[ "${TRAVIS_R_VERSION_STRING}"
+  = "release" ]]; then Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)' ;
+  fi fi
